### ISSUE TITLE
SFGUI incorrectly selects non-legacy renderer when GLSL 1.30 is not available.

### ISSUE THREAD

**Issue by nopoe** [TankOs/SFGUI#16]
SFGUI's non-legacy renderer seems to want GLSL 1.30, but in NonLegacyRenderer::IsAvailable(), it only checks to see if shaders are available. Internally, SFML seems to only check for GLSL 1.00 in the Shader::isAvailable() method. So any machine that's pre-1.30, but not quite pre-1.00, can't run SFGUI.

I have a pretty old laptop that I'd like to do development on but I can't get SFGUI to run because it keeps trying to use the non-legacy renderer and it fails to compile the vertex shader. Disabling the non-legacy renderer completely fixes the problem, but if there's an easy fix that could be done upstream, it would save me some headache.

Thanks!

**Comment by binary1248** [comment]
Should be fixed in 02e34e04b16b93398b72151d010c4545cd1264c9 in the testing branch.

**Comment by nopoe** [comment]
Awesome! I'll test it when I get home.

**Comment by nopoe** [comment]
The fix works on my pre-1.30 machine. Thanks again. :)
