### ISSUE TITLE
Rendering issues (text, texture edges)

### ISSUE THREAD

**Issue by TankOs** [TankOs/SFGUI#17]
While preparing the 0.3.0 release and testing the examples, I stumbled upon rendering issues. Additionally I can see the console output

> OpenGL extension SGIS_texture_edge_clamp unavailable
> Artifacts may occur along texture edges
> Ensure that hardware acceleration is enabled if available

Screenshot:

![2015-05-20-105508_1914x691_scrot](https://cloud.githubusercontent.com/assets/111807/7722313/36899540-fedf-11e4-84af-6b53920b492a.png)

Specs:

> % lspci | grep VGA
> 02:00.0 VGA compatible controller: NVIDIA Corporation GK104 [GeForce GTX 660 Ti] (rev a1)

> % glxinfo | grep SGIS_te
>    GL_SGIS_generate_mipmap, GL_SGIS_texture_lod, GL_SGIX_depth_texture, 
>    GL_SGIS_generate_mipmap, GL_SGIS_texture_lod, GL_SGIX_depth_texture, 

> % glxinfo | grep OpenGL
> OpenGL core profile version string: 4.4.0 NVIDIA 349.16
> OpenGL shading language version string: 4.50 NVIDIA

**Comment by eXpl0it3r** [comment]
https://github.com/SFML/SFML/issues/880

**Comment by TankOs** [comment]
Thanks, but I think this is not necessarily related, as SFML's examples for fine for me.

**Comment by binary1248** [comment]
It is caused by https://github.com/SFML/SFML/issues/880 like eXpl0it3r said. Your glxinfo output doesn't contain GL_SGIS_texture_edge_clamp, which is the only thing SFML currently looks for. SFGUI is also affected by this because we use sf::Texture all over the place. I already submitted a fix for that bug, no idea how the examples work for you without emitting any errors/warnings.

**Comment by TankOs** [comment]
They emit the warnings, but they look alright.

**Comment by binary1248** [comment]
It really depends on how the texture is sourced. The tighter the packing, the more likely the edges are going to look broken if CLAMP_TO_EDGE isn't used. SFML uses padding in `sf::Font` and depending on how the `sf::Sprite`'s textures are, you might or might not notice anything.

**Comment by TankOs** [comment]
Okay I see, thanks for the clarification.

**Comment by binary1248** [comment]
Fixed in SFML 2.3.1.

**Comment by TankOs** [comment]
Issue not gone with SFML 2.3.1. However I was able to reproduce it: When the test program starts in its original dimensions, everything looks fine:

![](http://i.imgur.com/416auBt.png)

When it's resized, it looks borked again:

![](http://i.imgur.com/cLA8GjR.png)

At first I didn't really recognize it, as the test program is the only example that allows the window to be resized, thus allowing my tiling WM to directly resize it. All the other examples force the WM to float them, i.e. keeping their requested dimensions.

**Comment by binary1248** [comment]
Same issue as [here](http://sfgui.sfml-dev.de/forum/topic453-texture-edge-clamp-problem-has-this-been-fixed-solved.html). FBO doesn't properly resize for some reason... will have to look into this.

**Comment by TankOs** [comment]
Hehe, should have checked the forum. :dancers:

**Comment by binary1248** [comment]
Should be fixed in bf0640e60ff947550334a28fd3ddfb9c2d1a05f5. Test and merge when ready.

**Comment by TankOs** [comment]
Perfect, it's working now, thanks. 0.3.0 is ready then.
