### ISSUE TITLE
Everything is good, but where is the lib file

### ISSUE THREAD

**Issue by ducklin5** [TankOs/SFGUI#18]
Everything seems to run well but no libxxxx.a file is generated to link to, isn't there supposed to be one

**Comment by eXpl0it3r** [comment]
On Linux?

**Comment by TankOs** [comment]
@ducklin5 http://sfgui.sfml-dev.de/p/faq#static_build

**Comment by ducklin5** [comment]
No, im on windows but i understand that to link to a library you need a  libxxxx-s.a ("s" for static),
@TankOs After the cmake build there is no file in the lib folder, and is FGUI_STATIC the only thing that I need or do i need to a link as well (for static)?

**Comment by eXpl0it3r** [comment]
I don't know what you're talking about then. Though I think this would better fit on the SFGUI forum than on the issue tracker. :wink:

Do you mean with "everything seems to run well" that you click "Configure" and "Generate" and CMake, but don't get any library file? If so then you need to actually build the library first. CMake only generates make or project files, which then can be used with the given toolchain to build (and install) the library.

**Comment by ducklin5** [comment]
oh okay, yes, you understand the problem. How am i supposed to build it?

**Comment by eXpl0it3r** [comment]
Depends on what toolchain you picked.

For MinGW it's `mingw32-make install`.
If you use MSYS with MinGW it's `make install`.
And for Visual Studio it's `nmake install` or using the project file, depending on what generator you used.

**Comment by ducklin5** [comment]
Okay, thank you! I got the lib file and by the way one of the example files doesnt compile
![compile_failure](https://cloud.githubusercontent.com/assets/7690321/7751978/a52771d2-ffe5-11e4-9932-81e7c854a31d.jpg)

**Comment by eXpl0it3r** [comment]
You need a C++11 compiler and/or one that supports `std::to_string`.
