### ISSUE TITLE
`gluPerspective` was not declared in this scope

### ISSUE THREAD

**Issue by Yuri20** [TankOs/SFGUI#19]
While compiling examples:

>/home/jerzy/Pobrane/SFGUI-0.2.3/examples/Canvas.cpp: In function ‘int main()’:
/home/jerzy/Pobrane/SFGUI-0.2.3/examples/Canvas.cpp:113:113: error: ‘gluPerspective’ was not declared in this scope
   gluPerspective( 90.f, opengl_canvas->GetAllocation().width / opengl_canvas->GetAllocation().height, 1.f, 20.f );

I am using g++ 4.9.2

**Comment by binary1248** [comment]
https://github.com/TankOs/SFGUI/blob/master/examples/Canvas.cpp

That line no longer exists.

Please don't report issues which don't apply to the current master revision of the library. Thank you.
