### ISSUE TITLE
CMake Warning Policy CMP0037

### ISSUE THREAD

**Issue by susnux** [TankOs/SFGUI#21]
CMake reports:

CMake Warning (dev) at examples/CMakeLists.txt:4 (add_executable):
  Policy CMP0037 is not set: Target names should not be reserved and should
  match a validity pattern.  Run "cmake --help-policy CMP0037" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The target name "test" is reserved or not valid for certain CMake features,
  such as generator expressions, and may result in undefined behavior.
Call Stack (most recent call first):
  examples/CMakeLists.txt:40 (build_example)
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by binary1248** [comment]
This was already fixed in master a long time ago.
