### ISSUE TITLE
Window disappears when trying to close it twice using the "X" button

### ISSUE THREAD

**Issue by Nvreformat** [TankOs/SFGUI#24]
Code sample reproducing the bug:  http://pastebin.com/HNdRJ9H3

Steps to reproduce:

1. Click the "Open Window" button
2. Close the new window using the X button on the title bar
3. Open the window again and try to close it. When you pass the mouse over it, it will either:

Disappear completely, as if it was closed.

Get attached to the mouse, as if you were moving it.

**Comment by binary1248** [comment]
Fixed in 65b54c5078d437d7cffa5426fc0607530bb1ce45.
