### ISSUE TITLE
ScrollSpeed doesn't get applied for the Notebook

### ISSUE THREAD

**Issue by eXpl0it3r** [TankOs/SFGUI#30]
The [BREW.cpp "claims"](https://github.com/TankOs/SFGUI/blob/master/src/SFGUI/Engines/BREW.cpp#L129) to set the `ScrollSpeed` property for the Notebook widget. However the [Notebook widget itself](https://github.com/TankOs/SFGUI/blob/master/src/SFGUI/Engines/BREW/Notebook.cpp#L22) never requests the setting from the theme.

I added the follow piece of code to the test example and nothing changed.

``` cpp
        "Notebook {"
        "   ScrollSpeed: 25.f;"
        "}"
```

Guess one of the main question is: Should `ScrollSpeed` be a property of the Notebook widget?

**Edit:** Only noticed just now that `ScrollSpeed` [is actually used](https://github.com/TankOs/SFGUI/blob/master/src/SFGUI/Notebook.cpp#L436) in the Notebook widget, but just not set any default. But I've yet to actually see it work...

**Comment by binary1248** [comment]
The `ScrollSpeed` property of a `sfg::Notebook` only affects the rate at which pages switch when making use of the arrow buttons that show up if there are too many tabs to display all at once.

Adding
```cpp
	sfg::Context::Get().GetEngine().SetProperties(
		"Notebook {"
		"   ScrollSpeed: 25.f;"
		"}"
	);
```
to the Notebook example yields the expected results.
