### ISSUE TITLE
Support for high resolution displays?

### ISSUE THREAD

**Issue by integricho** [TankOs/SFGUI#35]
Running the provided examples on high resolution displays (4k) result in all the widgets being rendered super small. Is there support for such displays already implemented maybe?

**Comment by binary1248** [comment]
What do you mean by "support for such displays"? SFGUI can already run on high resolution displays as you saw. Upscaling the size of the GUI or the render surface itself from a lower resolution isn't part of the GUI and should either be taken care of by the user (i.e. adjusting the sizes passed to SFGUI) or through SFML by stretching the RenderTarget to fill a larger area.

The fact that the examples don't take into account the resolution of the user's display doesn't mean that it can't be done in general. The examples would run just as poorly if you use a display with a really low resolution.

**Comment by integricho** [comment]
Ok, thanks, I'll take a look at it in more detail, I was just reviewing the possible UI toolkits for a tool, and as I saw the examples in that state I thought asking is quicker than looking at the API immediately.

**Comment by AlbertMpx** [comment]
I got the same issue as integricho : widgets appears very smalls. (SFGUI-0.3.2, SFML-2.4.2 on Win10)

Solved by adding : 
`SetProcessDpiAwareness(PROCESS_DPI_UNAWARE);`
at the start of main.

( The pb seems to be in the use of SetProcessDpiAwareness in SFML, I get the same behaviour if I create a Win32 window before SFML RenderWindow)
