### ISSUE TITLE
sfg::Canvas::Draw redefinition

### ISSUE THREAD

**Issue by Belfer** [TankOs/SFGUI#38]
In `void Draw( const sf::Vertex* vertices, unsigned int vertex_count, sf::PrimitiveType type, const sf::RenderStates& states = sf::RenderStates::Default );`

Why was Canvas::Draw parameter vertex_count given a type of unsigned int and not use SFML's std::size_t?
This is actually kind of a nuisance, any chance of a redefinition?

**Comment by binary1248** [comment]
Fixed in 8d7d62d0f5b81607b681b54d177a49876b6030f8.

**Comment by Belfer** [comment]
Not changed in Canvas.cpp

**Comment by Belfer** [comment]
Sent a pull request with fix.

**Comment by binary1248** [comment]
Fixed again in 9a9bcb90d3dc4cd96218bd81556aad6bdc7631f0.
