### ISSUE TITLE
[Suggestion] BitmapFonts

### ISSUE THREAD

**Issue by RUSshy** [TankOs/SFGUI#42]
Hello

For games good looking text is important, specially on mobile, some result like this can only be obtainaible using BitmapFont 

![t](https://cloud.githubusercontent.com/assets/18348637/23835151/9b53b824-0762-11e7-991d-ef7e967a7101.png)

Would be cool to be able to use, but that would requiere to write a parser for the xml or fnt format

What do you think ?

**Comment by eXpl0it3r** [comment]
Not sure what this has to do with SFGUI. SFGUI simply uses SFML for text rendering.

But don't go to the SFML repo on GitHub now to post the same issue. If you want to discuss an idea use the SFML forum and before you most make sure to search for existing threads with similar topics.

**Comment by RUSshy** [comment]
This is a GUI library, it is reponsible to draw text too, if you take libGDX for example Scene2D use BitmapFonts, it make more sense for games

**Comment by RUSshy** [comment]
I tried to connect to IRC to discuss about this but with KIWII i get a connection timeout error, i'll check on forum, sorry about this!

**Comment by eXpl0it3r** [comment]
The SFGUI channel is on the same server as the SFML channel, so you can also just use http://chat.sfml-dev.org/
However the SFGUI channel isn't as active, while many of your questions might also be answered in the SFML channel. :wink:
