### ISSUE TITLE
Nothing is rendered when using with a sf::RenderTexture

### ISSUE THREAD

**Issue by RUSshy** [TankOs/SFGUI#43]
Hello

I took the Hello World example, then tried to render the UI to a render texture, but nothing get rendered, it's all black

Here is a ready to use code to reproduce the issue:

https://gist.github.com/RUSshy/e8cca3746f4e610f8a5de771cefd44a9

**Comment by eXpl0it3r** [comment]
What SFGUI and what SFML version did you use?

**Comment by RUSshy** [comment]
I'm on macOS 10.12.3, i compiled SFGUI from source (this repo), and i'm using SFML 2.4.2 installed from brew

If i use the RenderWindow it works, but with a RenderTexture it doesn't

**Comment by eXpl0it3r** [comment]
SFGUI doesn't work with SFML 2.4.1 and newer, see #36. So maybe you're not using SFML 2.4.2 after all?

**Comment by RUSshy** [comment]
I rechecked brew and i'm using the 2.4.2 ^^

> Warning: sfml-2.4.2 already installed

I didn't know it wasn't working with >=2.4.1
That's weird that it's "semi" functional for me

I'll downgrade SFML then, thanks for info :)

**Comment by RUSshy** [comment]
I get same issue with 2.4.0 :/

**Comment by TankOs** [comment]
@binary1248 Any idea? Also how hard is it to make SFGUI compatible with 2.4.2? Can you give me some hints? I looked at it the other day, but frankly was lacking the overview to know where to start.

**Comment by TankOs** [comment]
@RUSshy SFGUI 0.3.2 just got released. Please try that and report back in case of errors.
