### ISSUE TITLE
[Q] are multiple windows supported?

### ISSUE THREAD

**Issue by esavier** [TankOs/SFGUI#44]
Hi,
I am developing a game in sfml with addition of sfgui, but we walked into a wall with window spawning
are multiple independent windows are supported in sfgui? By that i mean windows as sfml contexts, decorated with one or multiple buttons. Can you provide example in which multiple windows are spawned?

**Comment by eXpl0it3r** [comment]
Check out the main [SFGUI text example](https://github.com/TankOs/SFGUI/blob/master/examples/Test.cpp). It features all the available widgets and uses multiple windows. So yes, multiple windows are of course supported.

If you've run into an issue, let us know what problem you're facing.

**Comment by esavier** [comment]
yeah, i saw all examples provided, and i tested all, there is no example showing multiple windows feature in use. However i may not exactly correctly asked. 

### So to make it straight this is my use case:

 * currently main libraries are only libsfml and libsfgui since they are nicely talking to each other 👍 
 * i do want to create one main sf::RenderWindow which may or may not spawn unspecified number of additional, independent sf::RenderWindow objects (top level system windows) possibly sharing some data underneath.
 * multiple windows must work and be operable simulatinously (eg, either std::async or std::thread with mutex guards if needed)
 * each window must have ability to show sfgui components, but if i am not mistaken, if i manage to get opengl context launched it will work somehow since it is mainly just drawing.

### Now what i tried and what happened
I had some loooooong code, rather unreadable. so i quickly made the same mistakes on test.cpp example you kindly pointed me to.  After a little fight with cmake, and successfull compilation i have error from OpenGL that it couldn't activate context or (after adding mutexes) just two unresponsive although draggable white windows.

Full source is available [here](https://pastebin.com/r1bHCLd1)
this is basically raw test.cpp example with std::async and mutexes.

What am i doing wrong?

also, homepage documentation does not include sf::RenderWindow::hasFocus()

**Comment by eXpl0it3r** [comment]
Ah, I thought you were talking about multiple SFGUI windows. 😄

I don't know if SFGUI supports the use of multiple SFML windows, but I also don't really see the use case for that, especially since you can manage multiple windows in SFGUI itself.

I suggest you narrow down your example code to just having two windows and render two SFGUI windows. Because currently chances are that it's more an issue with your custom OpenGL code or mutex magic.

> also, homepage documentation does not include sf::RenderWindow::hasFocus()
It's documented on the [SFML website](https://www.sfml-dev.org/documentation/2.4.2/classsf_1_1Window.php#ac4dce670f07c5039a732ba0903ce3a77).

**Comment by esavier** [comment]
I am consistently having issue about opengl context being unable to initialize.
I am sure multiple contexts in case of SFML are supported - i did extensive research while searching for proper libraries and i am sure i managed to open two render windows easily. Something just preventing me to open more SFGUI interfaces on those contexts. 

I will make as simple example as possible and try to pinpoint specific issue, then i will post findings here. however it may take day or two.

i need multiple sfml windows since i want to make floating controls in separate window (multi monitor, strategy game) similarly how GIMP has canvas and toolbox in separate windows. I cant do it on SFGUI alone :)

**Comment by esavier** [comment]
ok, it took me faster than i expected.
i am attaching example (crashing) code, and most common, and hopefully reproducible stack trace (screen unfortunately). To reproduce crash, follow comment block (line 25)
Of course it is possible that i did something wrong, in which case please correct me!
[multiwindows_crash.zip](https://github.com/TankOs/SFGUI/files/1139147/multiwindows_crash.zip)

As I said earlier, it appears that sfg::SFGUI is a singleton, since there is no other calls to it later ( i am talking about components, like sfg::label or sfg::button)

It seems to be impossible to create two independent threads with independent SFGUI on them.
most noticeable is the segv in sf::Font::LoadGlyph() which i cant extract anything meaningful from, but i am almost sure it is correlated with multiple sfg::SFGUI objects.

**Comment by binary1248** [comment]
SFGUI is not thread safe. Accessing any SFGUI object from multiple threads simultaneously will lead to undefined behaviour.

The easiest way to render 2 GUIs to 2 SFML windows is to save pointers to the set of SFGUI windows that are supposed to be rendered onto each SFML window into a container. When rendering the GUI to one SFML window, hide the SFGUI windows displayed on the other and vice versa. Hiding and showing SFGUI widgets is not an expensive operation and can be done without significant performance overhead.
