### ISSUE TITLE
desktop.Remove(widget) & Widget remains on screen, becomes unresponsive

### ISSUE THREAD

**Issue by Zetal911** [TankOs/SFGUI#45]
Just what it says on the tin. The widget in question is a sfg::Window and I'm using the Signal OnCloseButton that comes with it. The signal definitely works (console prints out text when I click the close button), and clearly something happens since the Window becomes unresponsive afterwards, but the Window still remains on-screen.

I'm pretty new to both C++ and SFGUI, so I'd appreciate some clarification. So far as I can tell from the desktop.cpp example, I'm using the functions the same way as shown.

Thanks.

**Comment by binary1248** [comment]
Don't remove the widget when your are inside the signal handler. This will lead to undefined behaviour. Remember what you have to remove and remove it after your call to HandleEvent() returns.

**Comment by Zetal911** [comment]
Is there an example available that shows how to do this? (Desktop.cpp seems to 'remove' inside the signal handler, unless I'm misunderstanding the terminology?)

**Comment by binary1248** [comment]
In the case of Desktop.cpp, we first create another shared_ptr to the widget we want to remove, remove it and return from the handler. We also make sure not to try to manipulate the object too much. Once we remove it we must assume it is no longer safe to access. The example was written this way to stay short, and given its simplicity we could also manage the dangers that are associated with this method. We wouldn't recommend doing this in anything more complex than this scenario however.

**Comment by Zetal911** [comment]
Sorry to bother you again, but what do you mean by "Remember what you have to remove and remove it after your call to HandleEvent() returns."?

Does this mean storing the widget to be removed inside of a class or global variable and then deleting it inside of the while (mainWindow.pollEvent(event)) code block?

**Comment by binary1248** [comment]
> Does this mean storing the widget to be removed inside of a class or global variable and then deleting it inside of the while (mainWindow.pollEvent(event)) code block?

Yes.
