### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [TankOs/SFGUI#5]
Some parameters (like "[${SFML_INCLUDE_DIR}](https://github.com/TankOs/SFGUI/blob/596c7cec4539028c2d7b6b703e24437aaa07218a/CMakeLists.txt#L178)" and "[${PROJECT_BINARY_DIR}/doc](https://github.com/TankOs/SFGUI/blob/eb80dc08f419d0b8e39dc037738d8b37f118e96e/doc/CMakeLists.txt#L20)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like spaces.

I would recommend to apply [advices from a Wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes. "CMake splits arguments unless you use quotation marks or escapes.").

**Comment by binary1248** [comment]
Fixed in f181bdc2286632f5922b33b41af0d496e37f59a7.
