### ISSUE TITLE
Doxygen stuff doesn't seem to be generated

### ISSUE THREAD

**Issue by fl4shk** [TankOs/SFGUI#55]
I tried generating Doxygen stuff myself manually, but even then, it didn't seem to generate anything of use.  All I got was an index.html (and pngs and css files and whatnot for it).

**Comment by eXpl0it3r** [comment]
Doxygen generates HTML unless you tell it to generate a CHM or PDF and have the right tools ready.

Not sure how you approached it, but when you build SFGUI with CMake, you have an option to build the docs (`SFGUI_BUILD_DOC`) and if you check that and Doxygen is found by CMake, documentation will be generated.

**Comment by fl4shk** [comment]
Yeah I think I must have just screwed that up then.  I'll go ahead and close this issue then.
