### ISSUE TITLE
How to  display Chinese on sfgui

### ISSUE THREAD

**Issue by wu1274704958** [TankOs/SFGUI#56]
How to  display Chinese on sfgui

**Comment by eXpl0it3r** [comment]
1. Load a font that supports Chinese characters
2. Render Chinese text

Have you run into any issues?

**Comment by wu1274704958** [comment]
@eXpl0it3r  SFGUI::AddCharacterSet(u32,u32) How to call this function

**Comment by wu1274704958** [comment]
The sfml release library font.loadFromFile does not work properly while the debug library works well

**Comment by eXpl0it3r** [comment]
loadFromyFile works fine. If it can't find your font, then you need to check your individual working directory.

What do you intend to achieve with AddCharacterSet?

**Comment by binary1248** [comment]
You should try to get your font loaded and its glyphs displayed in SFML before trying with SFGUI. For SFML support, you can visit the SFML forum and ask there. As for your question regarding AddCharacterSet, just call the method on the `sfg::SFGUI` object you create:
```cpp
sfg::SFGUI sfgui;
sfgui.AddCharacterSet(someLowCodepoint, someHighCodepoint);
```
