### ISSUE TITLE
No obvious way to prevent window dragging.

### ISSUE THREAD

**Issue by hak33m16** [TankOs/SFGUI#63]
I've checked all the member functions I can think of that belong to all of the relative window-based functions in the example list. Is there something I've missed here?

**Comment by eXpl0it3r** [comment]
It's not really a natural way to handle windows. If a window has a title bar it's draggable.

You should be able to manually reset the position however.

**Comment by hak33m16** [comment]
Ah, see. I didn't realize that I was able to remove the title bar to prevent dragging. For anyone else who runs into this issue, just use the following line on your sfg::Window:

window->SetStyle(mainWindow->GetStyle() ^ sfg::Window::TITLEBAR);
