### ISSUE TITLE
sfgui apps crash immediately

### ISSUE THREAD

**Issue by bmajkut** [TankOs/SFGUI#64]
Hello,
I am new here. I work on small project. It is 2d game. I am using SFML and SFGUI. Everything works fine when I compile my project on Ubuntu and on several PC's with Windows 7. Unfortunately I have problem with sfgui on my notebook (i7, ddr3, win7-64). 
I have compiled sfml succesfully with mingw32 6.3. SFMLs examples works very good. SFGUI also compiled without any errors but when I want to start any example app it crashes. I have tried to debug it and i found that there is unhandeled exception in ig7icd32.dll. It is related to GLEW functions.
I attach screenshot:
![sfgui-exception](https://user-images.githubusercontent.com/4063537/41931556-bc82c4a6-797e-11e8-8ac5-fb3aa4d7b2ed.png)
Cmake settings for SFGUI:
![sfgui-cmake](https://user-images.githubusercontent.com/4063537/41931697-145aecb2-797f-11e8-98f7-706f3151591b.png)
Cmake settings for SFML:
![sfml-cmake](https://user-images.githubusercontent.com/4063537/41931741-3ef4b980-797f-11e8-93ae-70a65926c53d.png)

I dont know why it doesn't work just on this notebook.
Thanks in advance for any help!

**Comment by eXpl0it3r** [comment]
Try updating your graphics driver and/or make sure that it runs on your dedicated GPU. 😉 

SFGUI doesn't use GLEW so not sure what you mean by that.

**Comment by bmajkut** [comment]
Ive tried to find any solution to this on the internet. I found one or two threads about this exception and it led me to GLEW.

**Comment by eXpl0it3r** [comment]
`ig7icd32.dll` is your Intel driver, so make sure you're running the latest version or switch to your dedicated GPU if you have one.

**Comment by NewYaroslav** [comment]
I have exactly the same error. However, I noticed that the Layout program from the examples folder is working fine. The remaining examples give the same sortie.

**Comment by TankOs** [comment]
Can you guys provide us with a backtrace?

**Comment by galou** [comment]
Backtrace of `Window`'s crash:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff675e801 in __GI_abort () at abort.c:79
#2  0x00007ffff674e39a in __assert_fail_base (fmt=0x7ffff68d57d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7ffff79bbf45 "m_vertex_vbo != 0", 
    file=file@entry=0x7ffff79ba888 "/home/gael/04-sources/safelog/sfgui-src/src/SFGUI/Renderers/NonLegacyRenderer.cpp", line=line@entry=831, 
    function=function@entry=0x7ffff79bc560 <sfg::NonLegacyRenderer::SetupVAO()::__PRETTY_FUNCTION__> "void sfg::NonLegacyRenderer::SetupVAO()") at assert.c:92
#3  0x00007ffff674e412 in __GI___assert_fail (assertion=0x7ffff79bbf45 "m_vertex_vbo != 0", file=0x7ffff79ba888 "/home/gael/04-sources/safelog/sfgui-src/src/SFGUI/Renderers/NonLegacyRenderer.cpp", 
    line=831, function=0x7ffff79bc560 <sfg::NonLegacyRenderer::SetupVAO()::__PRETTY_FUNCTION__> "void sfg::NonLegacyRenderer::SetupVAO()") at assert.c:101
#4  0x00007ffff797916e in sfg::NonLegacyRenderer::SetupVAO (this=0x555555ac6730) at /home/gael/04-sources/safelog/sfgui-src/src/SFGUI/Renderers/NonLegacyRenderer.cpp:831
#5  0x00007ffff79761f9 in sfg::NonLegacyRenderer::DisplayImpl (this=0x555555ac6730) at /home/gael/04-sources/safelog/sfgui-src/src/SFGUI/Renderers/NonLegacyRenderer.cpp:341
#6  0x00007ffff7975f05 in sfg::NonLegacyRenderer::Display (this=0x555555ac6730, target=...) at /home/gael/04-sources/safelog/sfgui-src/src/SFGUI/Renderers/NonLegacyRenderer.cpp:294
#7  0x00007ffff798d1e9 in sfg::SFGUI::Display (this=0x7fffffffc477, target=...) at /home/gael/04-sources/safelog/sfgui-src/src/SFGUI/SFGUI.cpp:31
#8  0x0000555555556138 in main () at /home/gael/04-sources/safelog/sfgui-src/examples/Window.cpp:62
```

I have Ubuntu 18.04 on Lenovo Yoga 720 with Intel® UHD Graphics 620 (Kabylake GT2).

**Comment by galou** [comment]
Should we provide more information to help solving this issue?

**Comment by eXpl0it3r** [comment]
@galou Your issue seems unrelated to the one reported by OP.
For you it seems to crash in an assertion, which would indicate that your GPU doesn't support VBO. Make sure you have the latest graphics driver installed and that your Intel UHD Graphics 620 even supports VBOs.

**Comment by galou** [comment]
Thanks for the info and sorry for the noise.
