### ISSUE TITLE
Errors while batch build

### ISSUE THREAD

**Issue by Jadw1** [TankOs/SFGUI#68]
Hi,
I wanted to build SFGUI 0.4.0 so I've builded it in CMake
configure settings:
![](https://i.imgur.com/h1ebuQp.png)
(I had to pass path to sfml window/graphics/... library by hand)

![](https://i.imgur.com/FycTVmR.png)

Then, I wantet to do batch build in VS. I've selected ALL_BUILD and INSTALL, both in Debug and Release and I got these errors:
![](https://i.imgur.com/QkskMPF.png)

It's my first time using SFGUI so could u tell me what i'm doing wrong? :D

**Comment by DrBarbare** [comment]
Hi there,

Do you know how CMake was invoked? You mention having to specify SFML libraries path by hand... What is the first error message you encountered? Also, it looks like you are working from Visual Studio, do you have a more precise version?

Sorry for this long delay!

**Comment by DrBarbare** [comment]
Here is the steps I took to build on my Windows box today (full disclosure, I am a linux user at heart, so the following is command line interaction)

1. Configure the project using CMake;
    ```
    cmake -H".\" -B"Build" -DSFML_DIR="D:\Libraries\SFML32\SFML-2.5.0\lib\cmake\SFML\"
    ```
    > I provide CMake with the path to a file called `SFMLConfig.cmake`, which allows `find_package` to know where the libraries are.
2. Build using MSBUILD
    ```
    cmake --build Build -- /m
   ```
   > I had to check online how to do multicore build with MSBUILD, the option is `/m`.
3. Wait... Compilation takes much longer than on a unix-box ;)

It completes after a while with:
```
    23 Warning(s)
    0 Error(s)
```

Finally, I have:
```
SFGUI> ls .\Build\lib\Debug\

    Directory: SFGUI\Build\lib\Debug

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        1/19/2019   1:34 PM        3656704 sfgui-d.dll
-a----        1/19/2019   1:34 PM         215320 sfgui-d.exp
-a----        1/19/2019   1:34 PM       21160384 sfgui-d.ilk
-a----        1/19/2019   1:34 PM         352610 sfgui-d.lib
-a----        1/19/2019   1:34 PM       14929920 sfgui-d.pdb
```
