### ISSUE TITLE
Trying to use with codeblocks

### ISSUE THREAD

**Issue by James-Aylward** [TankOs/SFGUI#72]
So far I've done the steps on the SFML website to install this. I linked the static version of the library and when I run my program I get a "sfgui.dll was not found" error. How can I use SFGUI with codeblocks?

**Comment by Kostu96** [comment]
If you have this error that means you link agains dynamic sfgui, you have link against sfgui-s.lib and define SFGUI_STATIC in preprocesor. It's very similar to linking sfml staticly

**Comment by James-Aylward** [comment]
Thanks. Now I am getting the error "undefined reference to 'sfg::SFGUI::SFGUI()'

**Comment by eXpl0it3r** [comment]
What is your verbose build output? https://www.sfml-dev.org/faq.php#tr-grl-verbose-ide

**Comment by James-Aylward** [comment]
-------------- Build: Debug in SFML Maze Solver (compiler: GNU GCC Compiler)---------------

mingw32-g++.exe -L"C:\Program Files (x86)\CodeBlocks\SFGUI-0.3.2\lib" -L"C:\Program Files (x86)\CodeBlocks\SFML-2.4.2\lib" -o bin\Debug\ConwaysGameOfLife.exe obj\Debug\main.o obj\Debug\src\Application.o   -lsfml-graphics -lsfml-window -lsfml-system
obj\Debug\main.o: In function `main':
C:/Users/james/OneDrive/Documents/dev/C++/Maze Solver SFML/main.cpp:16: undefined reference to `_imp___ZN3sfg5SFGUIC1Ev'
C:/Users/james/OneDrive/Documents/dev/C++/Maze Solver SFML/main.cpp:16: undefined reference to `_imp___ZN3sfg5SFGUID1Ev'
collect2.exe: error: ld returned 1 exit status
Process terminated with status 1 (0 minute(s), 0 second(s))
3 error(s), 0 warning(s) (0 minute(s), 0 second(s))
 
Tried to recreate the error from before (I didn't save and I closed down codeblocks, which may have reset some settings) and now I'm getting a new error. Apologies for being stupid

**Comment by James-Aylward** [comment]
-------------- Build: Debug in SFML Maze Solver (compiler: GNU GCC Compiler)---------------

mingw32-g++.exe -Wall -fexceptions -DSFGUI_STATIC -std=c++11 -g -std=c++11 -g -Iinclude -I"C:\Program Files (x86)\CodeBlocks\SFGUI-0.3.2\include" -I"C:\Program Files (x86)\CodeBlocks\SFGUI-0.3.2\include" -I"C:\Program Files (x86)\CodeBlocks\SFML-2.4.2\include" -c "C:\Users\james\OneDrive\Documents\dev\C++\Maze Solver SFML\main.cpp" -o obj\Debug\main.o
mingw32-g++.exe -L"C:\Program Files (x86)\CodeBlocks\SFGUI-0.3.2\lib" -L"C:\Program Files (x86)\CodeBlocks\SFGUI-0.3.2\lib" -L"C:\Program Files (x86)\CodeBlocks\SFML-2.4.2\lib" -o bin\Debug\ConwaysGameOfLife.exe obj\Debug\main.o obj\Debug\src\Application.o   "C:\Program Files (x86)\CodeBlocks\SFGUI-0.3.2\lib\libsfgui-s.a" -lsfml-graphics -lsfml-window -lsfml-system
C:\Program Files (x86)\CodeBlocks\SFGUI-0.3.2\lib\libsfgui-s.a(SFGUI.cpp.obj):SFGUI.cpp:(.eh_frame+0x43): undefined reference to `__gxx_personality_v0'
C:\Program Files (x86)\CodeBlocks\SFGUI-0.3.2\lib\libsfgui-s.a(Renderer.cpp.obj):Renderer.cpp:(.text+0x2ac): undefined reference to `_Unwind_Resume'
C:\Program Files (x86)\CodeBlocks\SFGUI-0.3.2\lib\libsfgui-s.a(Renderer.cpp.obj):Renderer.cpp:(.text+0xec5): undefined reference to `_Unwind_Resume'
C:\Program Files (x86)\CodeBlocks\SFGUI-0.3.2\lib\libsfgui-s.a(Renderer.cpp.obj):Renderer.cpp:(.text+0xedb): undefined reference to `_Unwind_Resume'
C:\Program Files (x86)\CodeBlocks\SFGUI-0.3.2\lib\libsfgui-s.a(Renderer.cpp.obj):Renderer.cpp:(.text+0x10e8): undefined reference to `_Unwind_Resume'
C:\Program Files (x86)\CodeBlocks\SFGUI-0.3.2\lib\libsfgui-s.a(Renderer.cpp.obj):Renderer.cpp:(.text+0x20d6): undefined reference to `_Unwind_Resume'
C:\Program Files (x86)\CodeBlocks\SFGUI-0.3.2\lib\libsfgui-s.a(Renderer.cpp.obj):Renderer.cpp:(.text+0x20f8): more undefined references to `_Unwind_Resume' follow
C:\Program Files (x86)\CodeBlocks\SFGUI-0.3.2\lib\libsfgui-s.a(Renderer.cpp.obj):Renderer.cpp:(.text+0x3afc): undefined reference to `sf::String::begin[abi:cxx11]() const'
C:\Program Files (x86)\CodeBlocks\SFGUI-0.3.2\lib\libsfgui-s.a(Renderer.cpp.obj):Renderer.cpp:(.text+0x3b09): undefined reference to `sf::String::end[abi:cxx11]() const'
C:\Program Files (x86)\CodeBlocks\SFGUI-0.3.2\lib\libsfgui-s.a(Renderer.cpp.obj):Renderer.cpp:(.text+0x3f60): undefined reference to `_Unwind_Resume'
C:\Program Files (x86)\CodeBlocks\SFGUI-0.3.2\lib\libsfgui-s.a(Renderer.cpp.obj):Renderer.cpp:(.text+0x3f7a): undefined reference to `_Unwind_Resume'
C:\Program Files (x86)\CodeBlocks\SFGUI-0.3.2\lib\libsfgui-s.a(Renderer.cpp.obj):Renderer.cpp:(.text+0x3fd0): undefined reference to `_Unwind_Resume'
C:/Program Files (x86)/CodeBlocks/MinGW/bin/../lib/gcc/mingw32/4.9.2/../../../../mingw32/bin/ld.exe: C:\Program Files (x86)\CodeBlocks\SFGUI-0.3.2\lib\libsfgui-s.a(Renderer.cpp.obj): bad reloc address 0x7 in section `.text$_ZNSt23_Sp_counted_ptr_inplaceIN3sfg16RendererViewportESaIS1_ELN9__gnu_cxx12_Lock_policyE2EED0Ev[__ZNSt23_Sp_counted_ptr_inplaceIN3sfg16RendererViewportESaIS1_ELN9__gnu_cxx12_Lock_policyE2EED0Ev]'
collect2.exe: error: ld returned 1 exit status
Process terminated with status 1 (0 minute(s), 2 second(s))
13 error(s), 0 warning(s) (0 minute(s), 2 second(s))
 
I've relinked everything (using [this](https://www.sfml-dev.org/tutorials/2.5/start-cb.php) except for SFGUI) and this is the never verbose output.

**Comment by eXpl0it3r** [comment]
Personally, I'd strongly recommend to not mix static and dynamic libraries, unless you really know what you're doing. As such I'd recommend to link SFGUI dynamically (without `-s` suffix) as well.

There however still might be the chance, that SFML and SFGUI weren't built with the same compiler, which can lead to incompatibilities with the runtime.

**Comment by James-Aylward** [comment]
I have no idea what I'm doing, maybe I should just move on :(. Thanks for the help though, I'll hopefully get it working some day

**Comment by James-Aylward** [comment]
Ok, so I've done some reinstalling.

1. I uninstalled codeblocks-mingw (I was having some issues with the compiler included in that version)
2. I installed mingw on it's on and added it's bin directory to the path.
3. I reinstalled the basic codeblocks setup.
4. I removed my previous SFML version.
5. I downloaded the latest source code for SFML and built it statically.
6. I downloaded the latest source code for SFGUI and build it statically.
7. I followed the steps [here](https://www.sfml-dev.org/tutorials/2.5/start-cb.php) to try and use sfml on codeblocks.

The following is an image of my linker settings and the error message I get when I compile my SFML program
![image](https://user-images.githubusercontent.com/46735052/51973958-8f703500-24ca-11e9-835c-562d879550b2.png)

**Comment by eXpl0it3r** [comment]
In the linker settings you're not linking SFGUI.

**Comment by James-Aylward** [comment]
@eXpl0it3r I know, I uninstalled everything to start new and now I'm currently trying to get SFML working before SFGUI. I'll probably hop over to the SFML forums if this isn't the place to fix a (hopefully) quick SFML error.

**Comment by eXpl0it3r** [comment]
Looks like you added `C:\SFML\lib\sfml-xyz-s.a` to the general project settings, but also added `-lsfml-xyz` to the Release specific project settings.

If you want the dependencies listed in the general project settings, you need to make sure, that they are appended to the target specific project settings.
