### ISSUE TITLE
Undefined reference while trying to static linking with mingw32

### ISSUE THREAD

**Issue by bmajkut** [TankOs/SFGUI#78]
Hello Im trying to switch in my project to static version of SFML and SFGUI and I am stuck. My project work very well with dynamic linked library on Windows and Linux Ubuntu and Linux Fedora. I use CMake as a build system.
It is funny because I Dont know why sometimes I received .lib files and sometimes only .a files when I am compiling SFML by myself.
This is information about mingw32-g++:
`mingw32-g++.exe (MinGW.org GCC-6.3.0-1) 6.3.0`

I read instructions for SFML and SFGUI many times and I didnt find any valuable information to solve my problem. It will be really nice If someone could help me. Thanks in advance!

**Code:**
```
#include <SFML/Graphics.hpp>
#include <SFGUI/SFGUI.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(200, 200), "SFML works!");
    sf::CircleShape shape(100.f);
    shape.setFillColor(sf::Color::Green);
    sfg::SFGUI sfgui;
    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }
        window.clear();
        window.draw(shape);
        window.display();
    }
    return 0;
}
```
**Directory:**
![obraz](https://user-images.githubusercontent.com/4063537/64896986-09cc7e80-d682-11e9-8fd5-f30716bb1f00.png)
**Command:**
mingw32-g++.exe -c main.cpp -I.
mingw32-g++.exe main.o -L. -DSFML_STATIC -DSFGUI_STATIC -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lwinmm -lgdi32 -lfreetype -lSFGUI-s

**Output:**
```
main.o:main.cpp:(.text+0x7c): undefined reference to `_imp___ZN2sf6StringC1EPKcRKSt6locale'
main.o:main.cpp:(.text+0xa2): undefined reference to `_imp___ZN2sf9VideoModeC1Ejjj'
main.o:main.cpp:(.text+0xde): undefined reference to`_imp___ZN2sf12RenderWindowC1ENS_9VideoModeERKNS_6StringEjRKNS_15ContextSettingsE'
main.o:main.cpp:(.text+0x115): undefined reference to `_imp___ZN2sf11CircleShapeC1Efj'
main.o:main.cpp:(.text+0x126): undefined reference to `_imp___ZN2sf5Color5GreenE'
main.o:main.cpp:(.text+0x130): undefined reference to`_imp___ZN2sf5Shape12setFillColorERKNS_5ColorE'
main.o:main.cpp:(.text+0x142): undefined reference to `_imp___ZN3sfg5SFGUIC1Ev'
main.o:main.cpp:(.text+0x151): undefined reference to `_imp___ZNK2sf10WindowBase6isOpenEv'
main.o:main.cpp:(.text+0x171): undefined reference to`_imp___ZN2sf10WindowBase9pollEventERNS_5EventE'
main.o:main.cpp:(.text+0x191): undefined reference to `_imp___ZN2sf6Window5closeEv'
main.o:main.cpp:(.text+0x1be): undefined reference to `_imp___ZN2sf5ColorC1Ehhhh'
main.o:main.cpp:(.text+0x1d9): undefined reference to`_imp___ZN2sf12RenderTarget5clearERKNS_5ColorE'
main.o:main.cpp:(.text+0x1ec): undefined reference to `_imp___ZN2sf12RenderStates7DefaultE'
main.o:main.cpp:(.text+0x200): undefined reference to`_imp___ZN2sf12RenderTarget4drawERKNS_8DrawableERKNS_12RenderStatesE'
main.o:main.cpp:(.text+0x212): undefined reference to `_imp___ZN2sf6Window7displayEv'
main.o:main.cpp:(.text+0x22b): undefined reference to `_imp___ZN3sfg5SFGUID1Ev'
main.o:main.cpp:(.text+0x247): undefined reference to `_imp___ZN2sf12RenderWindowD1Ev'
main.o:main.cpp:(.text+0x280): undefined reference to `_imp___ZN3sfg5SFGUID1Ev'
main.o:main.cpp:(.text+0x2a4): undefined reference to `_imp___ZN2sf12RenderWindowD1Ev'
main.o:main.cpp:(.text$_ZN2sf11CircleShapeD1Ev[__ZN2sf11CircleShapeD1Ev]+0xa): undefined reference to `_imp___ZTVN2sf11CircleShapeE'
main.o:main.cpp:(.text$_ZN2sf11CircleShapeD1Ev[__ZN2sf11CircleShapeD1Ev]+0x17): undefinedreference to `_imp___ZTVN2sf11CircleShapeE'
main.o:main.cpp:(.text$_ZN2sf11CircleShapeD1Ev[__ZN2sf11CircleShapeD1Ev]+0x2a): undefinedreference to `_imp___ZN2sf5ShapeD2Ev'
collect2.exe: error: ld returned 1 exit status
```
**Cmake-gui:**
![obraz](https://user-images.githubusercontent.com/4063537/64897176-b60e6500-d682-11e9-9d58-7d4ff166e9dc.png)

![obraz](https://user-images.githubusercontent.com/4063537/64897187-c0c8fa00-d682-11e9-9e56-31ae32da0da9.png)

**Expected result:**
Build project with static version of SFML and static version of SFGUI

**Comment by DrBarbare** [comment]
I haven't had trouble building project on Windows with the MSVC toolchain. I usually just use the CMake generator options for it. If MinGW is not a requirement, you may want to go that way.

Now, this is not a solution, it's a workaround.

Were you able to use static libraries on Linux?
Were SFML and SFGUI built with the same toolchain?
Do you think SFGUI causes problem with your linking?

The linking error you have seem to indicate that SFML symbols cannot be resolved. Your command line look sane to me, but I am not a MinGW user. You mention having your project configured via CMake. Do you have CMake files to share? I am more versed in that technology ;).

For faster help and answers, I do recommend you ask on [the SFML discord](https://discord.gg/nr4X7Fh). People are really friendly to new comers!

**Comment by steevenakintilo** [comment]
fuck you
