### ISSUE TITLE
Global state

### ISSUE THREAD

**Issue by robinastedt** [TankOs/SFGUI#83]
So while trying to use sfgui I noticed my widgets remained as long as the instance was kept alive. It would be much nicer if the Display function took the root widget as an argument and only drew its children. Now I have to create new widgets on the fly and my own classes can't own pointers to its widgets since that means that they will always be drawn regardless. Also, global state is just bad... there is no need for this magic.

Also, is there a good reason we can't copy widgets?

**Comment by DrBarbare** [comment]
I am not sure I understand what you are trying to achieve. Widgets are handles via shared pointers, and as long as your Window contains a root widget, it will be redrawn (and with it, all the children).

In my personal project, I move my window pointer in a lambda, and while the function is alive, so is the widget tree. I do not need to keep pointers on widgets. I would however keep a weak pointer of an element I need to edit on the fly. This way, I do not compromise my state.

I never had to use global state (which is symptomatic of bad design, I agree). Is there a specific example of what you are having trouble with?

**Comment by robinastedt** [comment]
Thanks for your reply! In my project I use a class I call "Scene" which is a collection of various gui elements and logic for typically a menu layout, and I transition between these scenes. The various scene load in resources and preprocess a lot of graphics on initialization. I tried using the Desktop as a root object for these scenes, one in each, and when they are initialized all the children add their sfgui objects recursively. Then I draw everything from scene, sfgui and sfml objects all the way down recursively. However... the draw function in sfgui is for the global SFGUI object and does not take a widget nor desktop object as a parameter. It simply draws all desktops currently in memory, even though it shouldn't have any knowledge of them.

**Comment by eXpl0it3r** [comment]
Can you provide some minimal example, it's kind of hard to understand what you're doing.

If you're still referencing widgets e.g. through a box that was added to the desktop, then it will still be drawn. Note SFGUI is not an immediate mode GUI, but you need to actively maintain the state, i.e. add, remove or hide widgets.

**Comment by robinastedt** [comment]
Originally I thought just keeping Widgets alive would cause them to be drawn, even if I had removed them from the desktop object. However I can't seem to reproduce this anymore so I guess the error was on my part.

It still bothers me a bit though that I can't have several desktop objects with different widgets and select which to draw, but this I can work around fairly easily so I'll close the issue.
